// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Chain struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Item struct {
	ID        int64
	ChainID   int64
	StoreID   int64
	Category  string
	Code      pgtype.Int4
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Purchase struct {
	Day           pgtype.Date
	ChainID       int64
	StoreID       int64
	ReceiptID     int64
	ItemID        int64
	QuantityUnits pgtype.Int4
	PricePerUnit  pgtype.Numeric
	WeightPounds  pgtype.Numeric
	PricePerLb    pgtype.Numeric
	Price         pgtype.Numeric
	Sale          pgtype.Numeric
	Paid          pgtype.Numeric
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type Receipt struct {
	ID            int64
	StoreID       int64
	ReceiptNumber int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type Store struct {
	ID            int64
	ChainID       int64
	StoreNumber   int32
	StreetAddress string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}
