// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Chain struct {
	ChainID     int64
	Name        string
	Description pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type Grocery struct {
	GroceryID        int64
	ReceiptID        int64
	ItemID           int64
	Quantity         pgtype.Int4
	PricePerQuantity pgtype.Numeric
	Weight           pgtype.Numeric
	PricePerLb       pgtype.Numeric
	TotalPrice       pgtype.Numeric
	DiscountAmount   pgtype.Numeric
	TotalPaid        pgtype.Numeric
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
}

type Item struct {
	ItemID          int64
	ChainID         int64
	ItemNumber      int32
	ItemName        string
	ItemCategory    pgtype.Text
	ItemDescription pgtype.Text
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type Receipt struct {
	ReceiptID       int64
	StoreID         int64
	ReceiptNumber   int64
	TransactionDate time.Time
	FinalTotal      pgtype.Numeric
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type Store struct {
	StoreID       int64
	ChainID       int64
	StoreNumber   int32
	StreetAddress string
	Description   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type User struct {
	UserID    int64
	FirstName string
	LastName  string
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}
