// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChain = `-- name: CreateChain :execlastid
INSERT INTO chain (name) VALUES ($1)
`

const createItem = `-- name: CreateItem :execlastid
INSERT INTO item (chain_id, store_id, category, code, name) VALUES ($1, $2, $3, $4, $5)
`

type CreateItemParams struct {
	ChainID  int64
	StoreID  int64
	Category string
	Code     pgtype.Int4
	Name     string
}

const createPurchase = `-- name: CreatePurchase :execlastid
INSERT INTO purchases 
    (day, chain_id, store_id, receipt_id, item_id, quantity_units, price_per_unit, weight_pounds, price_per_lb, price, sale, paid) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreatePurchaseParams struct {
	Day           pgtype.Date
	ChainID       int64
	StoreID       int64
	ReceiptID     int64
	ItemID        int64
	QuantityUnits pgtype.Int4
	PricePerUnit  pgtype.Numeric
	WeightPounds  pgtype.Numeric
	PricePerLb    pgtype.Numeric
	Price         pgtype.Numeric
	Sale          pgtype.Numeric
	Paid          pgtype.Numeric
}

const createReceipt = `-- name: CreateReceipt :execlastid
INSERT INTO receipt (id, receipt_number) VALUES ($1, $2)
`

type CreateReceiptParams struct {
	ID            int64
	ReceiptNumber int64
}

const createStore = `-- name: CreateStore :execlastid
INSERT INTO store (chain_id, store_number, street_address) VALUES ($1, $2, $3)
`

type CreateStoreParams struct {
	ChainID       int64
	StoreNumber   int32
	StreetAddress string
}

const deleteChain = `-- name: DeleteChain :exec
DELETE FROM chain WHERE id = $1
`

func (q *Queries) DeleteChain(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteChain, id)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM item WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipt WHERE id = $1
`

func (q *Queries) DeleteReceipt(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReceipt, id)
	return err
}

const deleteStore = `-- name: DeleteStore :exec
DELETE FROM store WHERE id = $1
`

func (q *Queries) DeleteStore(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStore, id)
	return err
}

const getChain = `-- name: GetChain :one
SELECT id, name, created_at, updated_at, deleted_at FROM chain WHERE id = $1
`

func (q *Queries) GetChain(ctx context.Context, id int64) (Chain, error) {
	row := q.db.QueryRow(ctx, getChain, id)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, chain_id, store_id, category, code, name, created_at, updated_at, deleted_at FROM item WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.StoreID,
		&i.Category,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, store_id, receipt_number, created_at, updated_at, deleted_at FROM receipt WHERE id = $1
`

func (q *Queries) GetReceipt(ctx context.Context, id int64) (Receipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ReceiptNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStore = `-- name: GetStore :one
SELECT id, chain_id, store_number, street_address, created_at, updated_at, deleted_at FROM store WHERE id = $1
`

func (q *Queries) GetStore(ctx context.Context, id int64) (Store, error) {
	row := q.db.QueryRow(ctx, getStore, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.StoreNumber,
		&i.StreetAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
