-- Create "chains" table
CREATE TABLE "chains" ("chain_id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "name" text NOT NULL, "description" text NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("chain_id"));
-- Create "users" table
CREATE TABLE "users" ("user_id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "first_name" text NOT NULL, "last_name" text NOT NULL, "username" text NOT NULL, "password" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("user_id"), CONSTRAINT "users_username_key" UNIQUE ("username"));
-- Create "items" table
CREATE TABLE "items" ("item_id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "chain_id" bigint NOT NULL, "item_number" integer NOT NULL, "item_name" text NOT NULL, "item_category" text NULL, "item_description" text NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("item_id"), CONSTRAINT "items_chain_id_fkey" FOREIGN KEY ("chain_id") REFERENCES "chains" ("chain_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "stores" table
CREATE TABLE "stores" ("store_id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "chain_id" bigint NOT NULL, "store_number" integer NOT NULL, "street_address" text NOT NULL, "description" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("store_id"), CONSTRAINT "stores_chain_id_fkey" FOREIGN KEY ("chain_id") REFERENCES "chains" ("chain_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "reciepts" table
CREATE TABLE "reciepts" ("reciept_id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "store_id" bigint NOT NULL, "reciept_number" bigint NOT NULL, "transaction_date" timestamptz NOT NULL, "final_total" numeric(18,7) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("reciept_id"), CONSTRAINT "reciepts_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "groceries" table
CREATE TABLE "groceries" ("grocery_id" uuid NOT NULL, "reciept_id" bigint NOT NULL, "item_id" bigint NOT NULL, "quantity" integer NULL, "price_per_quantity" numeric(18,7) NULL, "weight" numeric(18,7) NULL, "price_per_lb" numeric(18,7) NULL, "total_price" numeric(18,7) NOT NULL, "discount_amount" numeric(18,7) NOT NULL, "total_paid" numeric(18,7) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("grocery_id"), CONSTRAINT "groceries_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items" ("item_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "groceries_reciept_id_fkey" FOREIGN KEY ("reciept_id") REFERENCES "reciepts" ("reciept_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
