openapi: 3.0.0
info:
  title: Rhea
  description: Traditional REST API for continued full-stack learning
  version: 0.1.0

servers:
  - url: http://www.localhost:8000/api/
    description: Optional server description, e.g. Main (production) server


# tags are used to group the endpoints
tags:
  - name: health
    description: Health checks

paths:
  /health:
    get:
      tags:
        - health
      summary: Returns a JSON object stating the server is healthy
      description: A heartbeat endpoint for the server, if the server is running, it should return healthy
      responses:
        "200": # status code
          description: A single JSON object with healthy status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                example:
                  status: healthy







  # /users:
  #   get:
  #     summary: Returns a list of users.
  #     description: Optional extended description in CommonMark or HTML.
  #     responses:
  #       "200": # status code
  #         description: A JSON array of user names
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 type: string
